// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1073.ApolloSimpleBot.subsystems;

import org.usfirst.frc1073.ApolloSimpleBot.RobotMap;
import org.usfirst.frc1073.ApolloSimpleBot.commands.*;
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.CANTalon.FeedbackDevice;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 *
 */
public class DriveTrain extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final CANTalon leftMotor1 = RobotMap.driveTrainleftMotor1;
    private final CANTalon leftMotor2 = RobotMap.driveTrainleftMotor2;
    private final CANTalon rightMotor1 = RobotMap.driveTrainrightMotor1;
    private final CANTalon rightMotor2 = RobotMap.driveTrainrightMotor2;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    boolean invertLeft = true;
    boolean invertRight = false;
    
    boolean invertLeftEncoder = false;
    boolean invertRightEncoder = false;
    
    public enum profiles {
    	SPEED,
    	POSITIONAL,
    	BASIC
    }
    
    private profiles current;
    private static final double MOTOR_RPM = 2150;
    
    public DriveTrain() {
    	
    	current = profiles.BASIC;
    	
    	setupMotors();
    	setupEncoders();
    	setupPID();
    }
    
    private void setupPID() {
    	leftMotor2.setFeedbackDevice(FeedbackDevice.QuadEncoder);
    	rightMotor1.setFeedbackDevice(FeedbackDevice.QuadEncoder);
    	
    	leftMotor2.configNominalOutputVoltage(+0f, -0f);
    	rightMotor1.configNominalOutputVoltage(+0f, -0f);
    	
    	leftMotor2.configPeakOutputVoltage(+12.0f, -12.0f);
    	rightMotor1.configPeakOutputVoltage(+12.0f, -12.0f);
    	
    	leftMotor2.setAllowableClosedLoopErr(0);
    	rightMotor1.setAllowableClosedLoopErr(0);
    }
    
    private void setupMotors() {
    	leftMotor1.setInverted(invertLeft);
    	leftMotor2.setInverted(invertLeft);
    	rightMotor1.setInverted(invertRight);
    	rightMotor1.setInverted(invertRight);
    	
    	leftMotor1.changeControlMode(CANTalon.TalonControlMode.Follower);
    	leftMotor1.set(leftMotor2.getDeviceID());
    	rightMotor2.changeControlMode(CANTalon.TalonControlMode.Follower);
    	rightMotor2.set(rightMotor1.getDeviceID());
    }
    
    private void setupEncoders() {
    	
    	leftMotor2.reverseSensor(invertLeftEncoder);
    	rightMotor1.reverseSensor(invertRightEncoder);
    	
    	leftMotor2.configEncoderCodesPerRev(360);
    	rightMotor1.configEncoderCodesPerRev(360);
    }
    
    public void manualSetProfile(profiles profile) {
    	if(profile.ordinal() != 0 || profile.ordinal() != 1) return;
    	else {
    		leftMotor2.setProfile(profile.ordinal());
    		rightMotor1.setProfile(profile.ordinal());
    	}
    }
    
    public void manualSetProfile(int id, double p, double i, double d) {
    	if(id != 0 || id != 1) return;
    	else {
    		leftMotor2.setProfile(id);
    		rightMotor1.setProfile(id);
    		
    		leftMotor2.setPID(p, i, d);
    		rightMotor1.setPID(p, i, d);
    	}
    }
    
    public void setPID(double p, double i, double d) {
    	leftMotor2.setPID(p, i, d);
		rightMotor1.setPID(p, i, d);
    }
    
    public void setPID(double p, double i, double d, double f) {
    	leftMotor2.setPID(p, i, d);
    	leftMotor2.setF(f);
		rightMotor1.setPID(p, i, d);
		rightMotor1.setF(f);
    }
    
    public void moveBasic(double left, double right) {
    	
    	if(getState() != CANTalon.TalonControlMode.PercentVbus) setBasic();
    	
    	leftMotor2.set(left);
    	rightMotor1.set(right);
    }
    
    public void movePIDSpeed(double leftSpeed, double rightSpeed) {
    	
    	if(getState() != CANTalon.TalonControlMode.Speed) setSpeedMode();
    	
    	leftMotor2.set(leftSpeed * MOTOR_RPM);
    	rightMotor1.set(rightSpeed * MOTOR_RPM);
    	
    }
    
    public void movePIDPositional(double leftDistance, double rightDistance) {
    	
    	if(getState() != CANTalon.TalonControlMode.Position) setPositional();
    	
    }
    
    public CANTalon.TalonControlMode getState() {
    	return leftMotor2.getControlMode();
    }
    
    public void setBasic() {
    	
    	current = profiles.BASIC;
    	
    	leftMotor2.changeControlMode(CANTalon.TalonControlMode.PercentVbus);
    	rightMotor1.changeControlMode(CANTalon.TalonControlMode.PercentVbus);
    }
    
    public void setSpeedMode() {
    	
    	current = profiles.SPEED;
    	
    	leftMotor2.setProfile(profiles.SPEED.ordinal());
    	rightMotor1.setProfile(profiles.SPEED.ordinal());
    	
    	leftMotor2.changeControlMode(CANTalon.TalonControlMode.Speed);
    	rightMotor1.changeControlMode(CANTalon.TalonControlMode.Speed);
    }
    
    public void setPositional() {
    	
    	current = profiles.POSITIONAL;
    	
    	leftMotor2.setProfile(profiles.POSITIONAL.ordinal());
    	rightMotor1.setProfile(profiles.POSITIONAL.ordinal());
    	
    	leftMotor2.changeControlMode(CANTalon.TalonControlMode.Position);
    	rightMotor1.changeControlMode(CANTalon.TalonControlMode.Position);
    }
    
    public double getLeftRawSpeed() {
    	return leftMotor2.getEncVelocity();
    }
    
    public double getRightRawSpeed() {
    	return rightMotor1.getEncVelocity();
    }

    public double getLeftRawDistance() {
    	return leftMotor2.getEncPosition();
    }
    
    public double getRightRawDistance() {
    	return rightMotor1.getEncPosition();
    }
    
    public profiles getCurrentProfile() {
    	return current;
    }
    
    public void setProfile(profiles newProfile) {
    	current = newProfile;
    }
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new Drive());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
}

